// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc60.superbot.commands;
import edu.wpi.first.wpilibj.command.Command;
import motionprofiles.magicMotionProfile;

import org.usfirst.frc60.superbot.Robot;
import org.usfirst.frc60.superbot.RobotMap;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;;
/**
 *
 */
public class MagicProfileTest extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public MagicProfileTest() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.drive);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    
    // Called just before this Command runs the first time
    protected void initialize() {
    	Robot.drive.setUpMagic();
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	if (!Robot.drive.isMagicked) {
    		Robot.drive.setUpMagic();
    	}
    	Robot.drive.setMagicPoint(1.0);
    	SmartDashboard.putString("LeftEnc", " " + RobotMap.driveLeftBack.getEncPosition());
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
    	//TODO
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    	//TODO
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    	Robot.drive.setVMode();
    }
}
