// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc60.superbot.subsystems;

import org.usfirst.frc60.superbot.RobotMap;
import org.usfirst.frc60.superbot.commands.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class GearHolder extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final SpeedController gearClampSpeedController = RobotMap.gearHolderGearClampSpeedController;
    private final SpeedController gearLiftSpeedController = RobotMap.gearHolderGearLiftSpeedController;
    private final Encoder gearLiftEncoder = RobotMap.gearHolderGearLiftEncoder;
    private final DigitalInput gearLiftUpSwitch = RobotMap.gearHolderGearLiftUpSwitch;
    private final DigitalInput gearLiftDownSwitch = RobotMap.gearHolderGearLiftDownSwitch;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private final double CLAMP_SPEED = 0.5;
    private final double UNCLAMP_SPEED = -0.5;

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }
    
    public void startClamping() {
    		gearClampSpeedController.set(CLAMP_SPEED);
    }
    public boolean isClamped() {
    	return false;		//TODO:
    }
    public void startUnclamping() {
    		gearClampSpeedController.set(UNCLAMP_SPEED);
    }
    public boolean isUnclamped() {
    	return true; 	//TODO
    }
    public void stopClampMotor() {
    	gearClampSpeedController.stopMotor();
    }
    
   
    public void tiltUp() {
    	
    }
    public boolean isTiltedUp() {
    	return true;
    }
    public void tiltDown() {
    	
    }
    public boolean isTiltedDown() {
    	return false;
    }
    public void stopTiltMotor() {
    	gearLiftSpeedController.stopMotor();
    }
}

