// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc60.superbot.subsystems;

import org.usfirst.frc60.superbot.RobotMap;
import org.usfirst.frc60.superbot.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon cANTalon1 = RobotMap.shooterCANTalon1;
    private final CANTalon cANTalon2 = RobotMap.shooterCANTalon2;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS


    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    	
    	cANTalon2.changeControlMode(CANTalon.TalonControlMode.Follower);
    	cANTalon2.set(cANTalon1.getDeviceID());
    	cANTalon2.reverseOutput(true);
    }
    	
    public void startflywheel() {
    	cANTalon1.set(0.75);
    }
    
    public void stop() {
    	cANTalon1.set(0);
    	cANTalon2.set(0);
    }
    
    public boolean isSpeedGood() {
    	if(cANTalon1.getEncVelocity() > 2) {
    		return true;
    	}else {
    		return false;
    	}
    }
}

