// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc60.superbot;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.Ultrasonic;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import com.kauailabs.navx.frc.*;
import edu.wpi.first.wpilibj.SPI;;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveLeftFront;
    public static CANTalon driveLeftBack;
    public static CANTalon driveRightFront;
    public static CANTalon driveRightBack;
    public static RobotDrive driveRobotDrive4;
    public static CANTalon shooterCANTalon1;
    public static CANTalon shooterCANTalon2;
    public static Ultrasonic navigationUltrasonic1;
    public static SpeedController gearHolderGearClampSpeedController;
    public static SpeedController gearHolderGearLiftSpeedController;
    public static Encoder gearHolderGearLiftEncoder;
    public static DigitalInput gearHolderGearLiftUpSwitch;
    public static DigitalInput gearHolderGearLiftDownSwitch;
    public static CANTalon fuelPickupFuelIntakeController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public static AHRS navx;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveLeftFront = new CANTalon(1);
        LiveWindow.addActuator("Drive", "Left Front", driveLeftFront);
        
        driveLeftBack = new CANTalon(2);
        LiveWindow.addActuator("Drive", "Left Back", driveLeftBack);
        
        driveRightFront = new CANTalon(3);
        LiveWindow.addActuator("Drive", "Right Front", driveRightFront);
        
        driveRightBack = new CANTalon(4);
        LiveWindow.addActuator("Drive", "Right Back", driveRightBack);
        
        driveRobotDrive4 = new RobotDrive(driveLeftFront, driveLeftBack,
              driveRightFront, driveRightBack);
        
        driveRobotDrive4.setSafetyEnabled(true);
        driveRobotDrive4.setExpiration(0.1);
        driveRobotDrive4.setSensitivity(0.5);
        driveRobotDrive4.setMaxOutput(1.0);

        driveRobotDrive4.setInvertedMotor(RobotDrive.MotorType.kFrontRight, true);
        driveRobotDrive4.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        shooterCANTalon1 = new CANTalon(5);
        LiveWindow.addActuator("Shooter", "CAN Talon 1", shooterCANTalon1);
        
        shooterCANTalon2 = new CANTalon(6);
        LiveWindow.addActuator("Shooter", "CAN Talon 2", shooterCANTalon2);
        
        navigationUltrasonic1 = new Ultrasonic(0, 1);
        LiveWindow.addSensor("Navigation", "Ultrasonic 1", navigationUltrasonic1);
        
        gearHolderGearClampSpeedController = new Talon(0);
        LiveWindow.addActuator("GearHolder", "GearClampSpeedController", (Talon) gearHolderGearClampSpeedController);
        
        gearHolderGearLiftSpeedController = new Talon(1);
        LiveWindow.addActuator("GearHolder", "GearLiftSpeedController", (Talon) gearHolderGearLiftSpeedController);
        
        gearHolderGearLiftEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("GearHolder", "GearLiftEncoder", gearHolderGearLiftEncoder);
        gearHolderGearLiftEncoder.setDistancePerPulse(1.0);
        gearHolderGearLiftEncoder.setPIDSourceType(PIDSourceType.kRate);
        gearHolderGearLiftUpSwitch = new DigitalInput(6);
        LiveWindow.addSensor("GearHolder", "GearLiftUpSwitch", gearHolderGearLiftUpSwitch);
        
        gearHolderGearLiftDownSwitch = new DigitalInput(7);
        LiveWindow.addSensor("GearHolder", "GearLiftDownSwitch", gearHolderGearLiftDownSwitch);
        
        fuelPickupFuelIntakeController = new CANTalon(7);
        LiveWindow.addActuator("FuelPickup", "FuelIntakeController", fuelPickupFuelIntakeController);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        navx = new AHRS(SPI.Port.kMXP);
    }
}
